version: "2"
linters:
  default: standard
  disable:
    - depguard
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

formatters:
  enable:
    - gci
    - golines

  exclusions:
    generated: strict