version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gopher_chess_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gopher_chess
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  migrate:
    image: arigaio/atlas:latest-alpine
    container_name: gopher_chess_migrate
    command:
      - migrate
      - apply
      - --dir
      - file:///migrations
      - --url
      - postgres://postgres:postgres@postgres:5432/gopher_chess?search_path=public&sslmode=disable
      - --revisions-schema
      - public
    volumes:
      - ./ent/migrate/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gopher_chess_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/gopher_chess?search_path=public&sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./ent/migrate/migrations:/app/ent/migrate/migrations

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://194.67.88.54:8000/v1
        - REACT_APP_WS_URL=ws://194.67.88.54:8000/v1
    container_name: gopher_chess_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: