version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15
    container_name: gopher_chess_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gopher_chess
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./ent/migrate/migrations:/docker-entrypoint-initdb.d/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Бэкенд сервис
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gopher_chess_backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/gopher_chess?search_path=public&sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./ent/migrate/migrations:/app/ent/migrate/migrations

  # Фронтенд сервис
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: gopher_chess_frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_WS_URL=ws://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: 