#!/usr/bin/env bash
set -e

psql --username "$DB_USER" <<-EOSQL
  CREATE ROLE IF NOT EXISTS ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  CREATE DATABASE IF NOT EXISTS ${DB_DATABASE} OWNER ${DB_USER};
EOSQL