// Code generated by ent_repository, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in GopherChessParty/ent_repository/runtime.go

const (
	Version = "v0.14.4"                                         // Version of ent_repository codegen.
	Sum     = "h1:/DhDraSLXIkBhyiVoJeSshr4ZYi7femzhj6/TckzZuI=" // Sum of ent_repository codegen.
)
