// Code generated by ent, DO NOT EDIT.

package chess

import (
	"GopherChessParty/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldID, id))
}

// FirstUserID applies equality check predicate on the "first_user_id" field. It's identical to FirstUserIDEQ.
func FirstUserID(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldFirstUserID, v))
}

// SecondUserID applies equality check predicate on the "second_user_id" field. It's identical to SecondUserIDEQ.
func SecondUserID(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldSecondUserID, v))
}

// Winner applies equality check predicate on the "winner" field. It's identical to WinnerEQ.
func Winner(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldWinner, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldUpdatedAt, v))
}

// FirstUserIDEQ applies the EQ predicate on the "first_user_id" field.
func FirstUserIDEQ(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldFirstUserID, v))
}

// FirstUserIDNEQ applies the NEQ predicate on the "first_user_id" field.
func FirstUserIDNEQ(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldFirstUserID, v))
}

// FirstUserIDIn applies the In predicate on the "first_user_id" field.
func FirstUserIDIn(vs ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldFirstUserID, vs...))
}

// FirstUserIDNotIn applies the NotIn predicate on the "first_user_id" field.
func FirstUserIDNotIn(vs ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldFirstUserID, vs...))
}

// FirstUserIDGT applies the GT predicate on the "first_user_id" field.
func FirstUserIDGT(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldFirstUserID, v))
}

// FirstUserIDGTE applies the GTE predicate on the "first_user_id" field.
func FirstUserIDGTE(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldFirstUserID, v))
}

// FirstUserIDLT applies the LT predicate on the "first_user_id" field.
func FirstUserIDLT(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldFirstUserID, v))
}

// FirstUserIDLTE applies the LTE predicate on the "first_user_id" field.
func FirstUserIDLTE(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldFirstUserID, v))
}

// SecondUserIDEQ applies the EQ predicate on the "second_user_id" field.
func SecondUserIDEQ(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldSecondUserID, v))
}

// SecondUserIDNEQ applies the NEQ predicate on the "second_user_id" field.
func SecondUserIDNEQ(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldSecondUserID, v))
}

// SecondUserIDIn applies the In predicate on the "second_user_id" field.
func SecondUserIDIn(vs ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldSecondUserID, vs...))
}

// SecondUserIDNotIn applies the NotIn predicate on the "second_user_id" field.
func SecondUserIDNotIn(vs ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldSecondUserID, vs...))
}

// SecondUserIDGT applies the GT predicate on the "second_user_id" field.
func SecondUserIDGT(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldSecondUserID, v))
}

// SecondUserIDGTE applies the GTE predicate on the "second_user_id" field.
func SecondUserIDGTE(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldSecondUserID, v))
}

// SecondUserIDLT applies the LT predicate on the "second_user_id" field.
func SecondUserIDLT(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldSecondUserID, v))
}

// SecondUserIDLTE applies the LTE predicate on the "second_user_id" field.
func SecondUserIDLTE(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldSecondUserID, v))
}

// WinnerEQ applies the EQ predicate on the "winner" field.
func WinnerEQ(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldWinner, v))
}

// WinnerNEQ applies the NEQ predicate on the "winner" field.
func WinnerNEQ(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldWinner, v))
}

// WinnerIn applies the In predicate on the "winner" field.
func WinnerIn(vs ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldWinner, vs...))
}

// WinnerNotIn applies the NotIn predicate on the "winner" field.
func WinnerNotIn(vs ...uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldWinner, vs...))
}

// WinnerGT applies the GT predicate on the "winner" field.
func WinnerGT(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldWinner, v))
}

// WinnerGTE applies the GTE predicate on the "winner" field.
func WinnerGTE(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldWinner, v))
}

// WinnerLT applies the LT predicate on the "winner" field.
func WinnerLT(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldWinner, v))
}

// WinnerLTE applies the LTE predicate on the "winner" field.
func WinnerLTE(v uuid.UUID) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldWinner, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Chess {
	return predicate.Chess(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chess) predicate.Chess {
	return predicate.Chess(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chess) predicate.Chess {
	return predicate.Chess(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chess) predicate.Chess {
	return predicate.Chess(sql.NotPredicates(p))
}
