env: "local"
database:
  dbHost: "localhost"
  dbPort: 5432
  dbUser: "postgres"
  dbPassword: "postgres"
  dbDatabase: "gopher_chess"
auth:
  SecretAccess: "SecretAccess"
  SecretRefresh: "SecretRefresh"