// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChessesColumns holds the columns for the "chesses" table.
	ChessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "status", Type: field.TypeUint8, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_chesses_as_first", Type: field.TypeUUID, Nullable: true},
		{Name: "user_chesses_as_second", Type: field.TypeUUID, Nullable: true},
		{Name: "user_chesses_won", Type: field.TypeUUID, Nullable: true},
	}
	// ChessesTable holds the schema information for the "chesses" table.
	ChessesTable = &schema.Table{
		Name:       "chesses",
		Columns:    ChessesColumns,
		PrimaryKey: []*schema.Column{ChessesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chesses_users_chesses_as_first",
				Columns:    []*schema.Column{ChessesColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "chesses_users_chesses_as_second",
				Columns:    []*schema.Column{ChessesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "chesses_users_chesses_won",
				Columns:    []*schema.Column{ChessesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "password", Type: field.TypeString, Size: 255},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChessesTable,
		UsersTable,
	}
)

func init() {
	ChessesTable.ForeignKeys[0].RefTable = UsersTable
	ChessesTable.ForeignKeys[1].RefTable = UsersTable
	ChessesTable.ForeignKeys[2].RefTable = UsersTable
}
