// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GopherChessParty/ent/chess"
	"GopherChessParty/ent/gamehistory"
	"GopherChessParty/ent/predicate"
	"GopherChessParty/ent/user"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChessQuery is the builder for querying Chess entities.
type ChessQuery struct {
	config
	ctx           *QueryContext
	order         []chess.OrderOption
	inters        []Interceptor
	predicates    []predicate.Chess
	withWhiteUser *UserQuery
	withBlackUser *UserQuery
	withMoves     *GameHistoryQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChessQuery builder.
func (cq *ChessQuery) Where(ps ...predicate.Chess) *ChessQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ChessQuery) Limit(limit int) *ChessQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ChessQuery) Offset(offset int) *ChessQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ChessQuery) Unique(unique bool) *ChessQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ChessQuery) Order(o ...chess.OrderOption) *ChessQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryWhiteUser chains the current query on the "white_user" edge.
func (cq *ChessQuery) QueryWhiteUser() *UserQuery {
	query := (&UserClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chess.Table, chess.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chess.WhiteUserTable, chess.WhiteUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBlackUser chains the current query on the "black_user" edge.
func (cq *ChessQuery) QueryBlackUser() *UserQuery {
	query := (&UserClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chess.Table, chess.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chess.BlackUserTable, chess.BlackUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMoves chains the current query on the "moves" edge.
func (cq *ChessQuery) QueryMoves() *GameHistoryQuery {
	query := (&GameHistoryClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chess.Table, chess.FieldID, selector),
			sqlgraph.To(gamehistory.Table, gamehistory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, chess.MovesTable, chess.MovesColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Chess entity from the query.
// Returns a *NotFoundError when no Chess was found.
func (cq *ChessQuery) First(ctx context.Context) (*Chess, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chess.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ChessQuery) FirstX(ctx context.Context) *Chess {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Chess ID from the query.
// Returns a *NotFoundError when no Chess ID was found.
func (cq *ChessQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chess.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ChessQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Chess entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Chess entity is found.
// Returns a *NotFoundError when no Chess entities are found.
func (cq *ChessQuery) Only(ctx context.Context) (*Chess, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chess.Label}
	default:
		return nil, &NotSingularError{chess.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ChessQuery) OnlyX(ctx context.Context) *Chess {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Chess ID in the query.
// Returns a *NotSingularError when more than one Chess ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ChessQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chess.Label}
	default:
		err = &NotSingularError{chess.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ChessQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Chesses.
func (cq *ChessQuery) All(ctx context.Context) ([]*Chess, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Chess, *ChessQuery]()
	return withInterceptors[[]*Chess](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ChessQuery) AllX(ctx context.Context) []*Chess {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Chess IDs.
func (cq *ChessQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(chess.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ChessQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ChessQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ChessQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ChessQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ChessQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ChessQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChessQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ChessQuery) Clone() *ChessQuery {
	if cq == nil {
		return nil
	}
	return &ChessQuery{
		config:        cq.config,
		ctx:           cq.ctx.Clone(),
		order:         append([]chess.OrderOption{}, cq.order...),
		inters:        append([]Interceptor{}, cq.inters...),
		predicates:    append([]predicate.Chess{}, cq.predicates...),
		withWhiteUser: cq.withWhiteUser.Clone(),
		withBlackUser: cq.withBlackUser.Clone(),
		withMoves:     cq.withMoves.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithWhiteUser tells the query-builder to eager-load the nodes that are connected to
// the "white_user" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ChessQuery) WithWhiteUser(opts ...func(*UserQuery)) *ChessQuery {
	query := (&UserClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withWhiteUser = query
	return cq
}

// WithBlackUser tells the query-builder to eager-load the nodes that are connected to
// the "black_user" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ChessQuery) WithBlackUser(opts ...func(*UserQuery)) *ChessQuery {
	query := (&UserClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withBlackUser = query
	return cq
}

// WithMoves tells the query-builder to eager-load the nodes that are connected to
// the "moves" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ChessQuery) WithMoves(opts ...func(*GameHistoryQuery)) *ChessQuery {
	query := (&GameHistoryClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withMoves = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Chess.Query().
//		GroupBy(chess.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ChessQuery) GroupBy(field string, fields ...string) *ChessGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChessGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = chess.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Chess.Query().
//		Select(chess.FieldCreatedAt).
//		Scan(ctx, &v)
func (cq *ChessQuery) Select(fields ...string) *ChessSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ChessSelect{ChessQuery: cq}
	sbuild.label = chess.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChessSelect configured with the given aggregations.
func (cq *ChessQuery) Aggregate(fns ...AggregateFunc) *ChessSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ChessQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !chess.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ChessQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Chess, error) {
	var (
		nodes       = []*Chess{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [3]bool{
			cq.withWhiteUser != nil,
			cq.withBlackUser != nil,
			cq.withMoves != nil,
		}
	)
	if cq.withWhiteUser != nil || cq.withBlackUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, chess.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Chess).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Chess{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withWhiteUser; query != nil {
		if err := cq.loadWhiteUser(ctx, query, nodes, nil,
			func(n *Chess, e *User) { n.Edges.WhiteUser = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withBlackUser; query != nil {
		if err := cq.loadBlackUser(ctx, query, nodes, nil,
			func(n *Chess, e *User) { n.Edges.BlackUser = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withMoves; query != nil {
		if err := cq.loadMoves(ctx, query, nodes,
			func(n *Chess) { n.Edges.Moves = []*GameHistory{} },
			func(n *Chess, e *GameHistory) { n.Edges.Moves = append(n.Edges.Moves, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ChessQuery) loadWhiteUser(ctx context.Context, query *UserQuery, nodes []*Chess, init func(*Chess), assign func(*Chess, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Chess)
	for i := range nodes {
		if nodes[i].user_white_id == nil {
			continue
		}
		fk := *nodes[i].user_white_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_white_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *ChessQuery) loadBlackUser(ctx context.Context, query *UserQuery, nodes []*Chess, init func(*Chess), assign func(*Chess, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Chess)
	for i := range nodes {
		if nodes[i].user_black_id == nil {
			continue
		}
		fk := *nodes[i].user_black_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_black_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *ChessQuery) loadMoves(ctx context.Context, query *GameHistoryQuery, nodes []*Chess, init func(*Chess), assign func(*Chess, *GameHistory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Chess)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(gamehistory.FieldGameID)
	}
	query.Where(predicate.GameHistory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(chess.MovesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GameID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "game_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *ChessQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ChessQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chess.Table, chess.Columns, sqlgraph.NewFieldSpec(chess.FieldID, field.TypeUUID))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chess.FieldID)
		for i := range fields {
			if fields[i] != chess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ChessQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(chess.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = chess.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChessGroupBy is the group-by builder for Chess entities.
type ChessGroupBy struct {
	selector
	build *ChessQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ChessGroupBy) Aggregate(fns ...AggregateFunc) *ChessGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ChessGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChessQuery, *ChessGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ChessGroupBy) sqlScan(ctx context.Context, root *ChessQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChessSelect is the builder for selecting fields of Chess entities.
type ChessSelect struct {
	*ChessQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ChessSelect) Aggregate(fns ...AggregateFunc) *ChessSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ChessSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChessQuery, *ChessSelect](ctx, cs.ChessQuery, cs, cs.inters, v)
}

func (cs *ChessSelect) sqlScan(ctx context.Context, root *ChessQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
