// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GopherChessParty/ent/chess"
	"GopherChessParty/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChessUpdate is the builder for updating Chess entities.
type ChessUpdate struct {
	config
	hooks    []Hook
	mutation *ChessMutation
}

// Where appends a list predicates to the ChessUpdate builder.
func (cu *ChessUpdate) Where(ps ...predicate.Chess) *ChessUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetFirstUserID sets the "first_user_id" field.
func (cu *ChessUpdate) SetFirstUserID(u uuid.UUID) *ChessUpdate {
	cu.mutation.SetFirstUserID(u)
	return cu
}

// SetNillableFirstUserID sets the "first_user_id" field if the given value is not nil.
func (cu *ChessUpdate) SetNillableFirstUserID(u *uuid.UUID) *ChessUpdate {
	if u != nil {
		cu.SetFirstUserID(*u)
	}
	return cu
}

// SetSecondUserID sets the "second_user_id" field.
func (cu *ChessUpdate) SetSecondUserID(u uuid.UUID) *ChessUpdate {
	cu.mutation.SetSecondUserID(u)
	return cu
}

// SetNillableSecondUserID sets the "second_user_id" field if the given value is not nil.
func (cu *ChessUpdate) SetNillableSecondUserID(u *uuid.UUID) *ChessUpdate {
	if u != nil {
		cu.SetSecondUserID(*u)
	}
	return cu
}

// SetWinner sets the "winner" field.
func (cu *ChessUpdate) SetWinner(u uuid.UUID) *ChessUpdate {
	cu.mutation.SetWinner(u)
	return cu
}

// SetNillableWinner sets the "winner" field if the given value is not nil.
func (cu *ChessUpdate) SetNillableWinner(u *uuid.UUID) *ChessUpdate {
	if u != nil {
		cu.SetWinner(*u)
	}
	return cu
}

// SetStatus sets the "status" field.
func (cu *ChessUpdate) SetStatus(u uint8) *ChessUpdate {
	cu.mutation.ResetStatus()
	cu.mutation.SetStatus(u)
	return cu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cu *ChessUpdate) SetNillableStatus(u *uint8) *ChessUpdate {
	if u != nil {
		cu.SetStatus(*u)
	}
	return cu
}

// AddStatus adds u to the "status" field.
func (cu *ChessUpdate) AddStatus(u int8) *ChessUpdate {
	cu.mutation.AddStatus(u)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *ChessUpdate) SetCreatedAt(t time.Time) *ChessUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *ChessUpdate) SetNillableCreatedAt(t *time.Time) *ChessUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ChessUpdate) SetUpdatedAt(t time.Time) *ChessUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *ChessUpdate) SetNillableUpdatedAt(t *time.Time) *ChessUpdate {
	if t != nil {
		cu.SetUpdatedAt(*t)
	}
	return cu
}

// Mutation returns the ChessMutation object of the builder.
func (cu *ChessUpdate) Mutation() *ChessMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChessUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChessUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChessUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChessUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ChessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chess.Table, chess.Columns, sqlgraph.NewFieldSpec(chess.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.FirstUserID(); ok {
		_spec.SetField(chess.FieldFirstUserID, field.TypeUUID, value)
	}
	if value, ok := cu.mutation.SecondUserID(); ok {
		_spec.SetField(chess.FieldSecondUserID, field.TypeUUID, value)
	}
	if value, ok := cu.mutation.Winner(); ok {
		_spec.SetField(chess.FieldWinner, field.TypeUUID, value)
	}
	if value, ok := cu.mutation.Status(); ok {
		_spec.SetField(chess.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := cu.mutation.AddedStatus(); ok {
		_spec.AddField(chess.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(chess.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(chess.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChessUpdateOne is the builder for updating a single Chess entity.
type ChessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChessMutation
}

// SetFirstUserID sets the "first_user_id" field.
func (cuo *ChessUpdateOne) SetFirstUserID(u uuid.UUID) *ChessUpdateOne {
	cuo.mutation.SetFirstUserID(u)
	return cuo
}

// SetNillableFirstUserID sets the "first_user_id" field if the given value is not nil.
func (cuo *ChessUpdateOne) SetNillableFirstUserID(u *uuid.UUID) *ChessUpdateOne {
	if u != nil {
		cuo.SetFirstUserID(*u)
	}
	return cuo
}

// SetSecondUserID sets the "second_user_id" field.
func (cuo *ChessUpdateOne) SetSecondUserID(u uuid.UUID) *ChessUpdateOne {
	cuo.mutation.SetSecondUserID(u)
	return cuo
}

// SetNillableSecondUserID sets the "second_user_id" field if the given value is not nil.
func (cuo *ChessUpdateOne) SetNillableSecondUserID(u *uuid.UUID) *ChessUpdateOne {
	if u != nil {
		cuo.SetSecondUserID(*u)
	}
	return cuo
}

// SetWinner sets the "winner" field.
func (cuo *ChessUpdateOne) SetWinner(u uuid.UUID) *ChessUpdateOne {
	cuo.mutation.SetWinner(u)
	return cuo
}

// SetNillableWinner sets the "winner" field if the given value is not nil.
func (cuo *ChessUpdateOne) SetNillableWinner(u *uuid.UUID) *ChessUpdateOne {
	if u != nil {
		cuo.SetWinner(*u)
	}
	return cuo
}

// SetStatus sets the "status" field.
func (cuo *ChessUpdateOne) SetStatus(u uint8) *ChessUpdateOne {
	cuo.mutation.ResetStatus()
	cuo.mutation.SetStatus(u)
	return cuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cuo *ChessUpdateOne) SetNillableStatus(u *uint8) *ChessUpdateOne {
	if u != nil {
		cuo.SetStatus(*u)
	}
	return cuo
}

// AddStatus adds u to the "status" field.
func (cuo *ChessUpdateOne) AddStatus(u int8) *ChessUpdateOne {
	cuo.mutation.AddStatus(u)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *ChessUpdateOne) SetCreatedAt(t time.Time) *ChessUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *ChessUpdateOne) SetNillableCreatedAt(t *time.Time) *ChessUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ChessUpdateOne) SetUpdatedAt(t time.Time) *ChessUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *ChessUpdateOne) SetNillableUpdatedAt(t *time.Time) *ChessUpdateOne {
	if t != nil {
		cuo.SetUpdatedAt(*t)
	}
	return cuo
}

// Mutation returns the ChessMutation object of the builder.
func (cuo *ChessUpdateOne) Mutation() *ChessMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ChessUpdate builder.
func (cuo *ChessUpdateOne) Where(ps ...predicate.Chess) *ChessUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChessUpdateOne) Select(field string, fields ...string) *ChessUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chess entity.
func (cuo *ChessUpdateOne) Save(ctx context.Context) (*Chess, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChessUpdateOne) SaveX(ctx context.Context) *Chess {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChessUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChessUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ChessUpdateOne) sqlSave(ctx context.Context) (_node *Chess, err error) {
	_spec := sqlgraph.NewUpdateSpec(chess.Table, chess.Columns, sqlgraph.NewFieldSpec(chess.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chess.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chess.FieldID)
		for _, f := range fields {
			if !chess.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.FirstUserID(); ok {
		_spec.SetField(chess.FieldFirstUserID, field.TypeUUID, value)
	}
	if value, ok := cuo.mutation.SecondUserID(); ok {
		_spec.SetField(chess.FieldSecondUserID, field.TypeUUID, value)
	}
	if value, ok := cuo.mutation.Winner(); ok {
		_spec.SetField(chess.FieldWinner, field.TypeUUID, value)
	}
	if value, ok := cuo.mutation.Status(); ok {
		_spec.SetField(chess.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := cuo.mutation.AddedStatus(); ok {
		_spec.AddField(chess.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(chess.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(chess.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Chess{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
