// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"GopherChessParty/ent/chess"
	"GopherChessParty/ent/gamehistory"
	"GopherChessParty/ent/predicate"
	"GopherChessParty/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// GameHistoryQuery is the builder for querying GameHistory entities.
type GameHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []gamehistory.OrderOption
	inters     []Interceptor
	predicates []predicate.GameHistory
	withUser   *UserQuery
	withGame   *ChessQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GameHistoryQuery builder.
func (ghq *GameHistoryQuery) Where(ps ...predicate.GameHistory) *GameHistoryQuery {
	ghq.predicates = append(ghq.predicates, ps...)
	return ghq
}

// Limit the number of records to be returned by this query.
func (ghq *GameHistoryQuery) Limit(limit int) *GameHistoryQuery {
	ghq.ctx.Limit = &limit
	return ghq
}

// Offset to start from.
func (ghq *GameHistoryQuery) Offset(offset int) *GameHistoryQuery {
	ghq.ctx.Offset = &offset
	return ghq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ghq *GameHistoryQuery) Unique(unique bool) *GameHistoryQuery {
	ghq.ctx.Unique = &unique
	return ghq
}

// Order specifies how the records should be ordered.
func (ghq *GameHistoryQuery) Order(o ...gamehistory.OrderOption) *GameHistoryQuery {
	ghq.order = append(ghq.order, o...)
	return ghq
}

// QueryUser chains the current query on the "user" edge.
func (ghq *GameHistoryQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ghq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ghq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ghq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamehistory.Table, gamehistory.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gamehistory.UserTable, gamehistory.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ghq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGame chains the current query on the "game" edge.
func (ghq *GameHistoryQuery) QueryGame() *ChessQuery {
	query := (&ChessClient{config: ghq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ghq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ghq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(gamehistory.Table, gamehistory.FieldID, selector),
			sqlgraph.To(chess.Table, chess.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, gamehistory.GameTable, gamehistory.GameColumn),
		)
		fromU = sqlgraph.SetNeighbors(ghq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GameHistory entity from the query.
// Returns a *NotFoundError when no GameHistory was found.
func (ghq *GameHistoryQuery) First(ctx context.Context) (*GameHistory, error) {
	nodes, err := ghq.Limit(1).All(setContextOp(ctx, ghq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{gamehistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ghq *GameHistoryQuery) FirstX(ctx context.Context) *GameHistory {
	node, err := ghq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GameHistory ID from the query.
// Returns a *NotFoundError when no GameHistory ID was found.
func (ghq *GameHistoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ghq.Limit(1).IDs(setContextOp(ctx, ghq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{gamehistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ghq *GameHistoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ghq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GameHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GameHistory entity is found.
// Returns a *NotFoundError when no GameHistory entities are found.
func (ghq *GameHistoryQuery) Only(ctx context.Context) (*GameHistory, error) {
	nodes, err := ghq.Limit(2).All(setContextOp(ctx, ghq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{gamehistory.Label}
	default:
		return nil, &NotSingularError{gamehistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ghq *GameHistoryQuery) OnlyX(ctx context.Context) *GameHistory {
	node, err := ghq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GameHistory ID in the query.
// Returns a *NotSingularError when more than one GameHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (ghq *GameHistoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ghq.Limit(2).IDs(setContextOp(ctx, ghq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{gamehistory.Label}
	default:
		err = &NotSingularError{gamehistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ghq *GameHistoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ghq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GameHistories.
func (ghq *GameHistoryQuery) All(ctx context.Context) ([]*GameHistory, error) {
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryAll)
	if err := ghq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GameHistory, *GameHistoryQuery]()
	return withInterceptors[[]*GameHistory](ctx, ghq, qr, ghq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ghq *GameHistoryQuery) AllX(ctx context.Context) []*GameHistory {
	nodes, err := ghq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GameHistory IDs.
func (ghq *GameHistoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if ghq.ctx.Unique == nil && ghq.path != nil {
		ghq.Unique(true)
	}
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryIDs)
	if err = ghq.Select(gamehistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ghq *GameHistoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ghq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ghq *GameHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryCount)
	if err := ghq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ghq, querierCount[*GameHistoryQuery](), ghq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ghq *GameHistoryQuery) CountX(ctx context.Context) int {
	count, err := ghq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ghq *GameHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ghq.ctx, ent.OpQueryExist)
	switch _, err := ghq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ghq *GameHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := ghq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GameHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ghq *GameHistoryQuery) Clone() *GameHistoryQuery {
	if ghq == nil {
		return nil
	}
	return &GameHistoryQuery{
		config:     ghq.config,
		ctx:        ghq.ctx.Clone(),
		order:      append([]gamehistory.OrderOption{}, ghq.order...),
		inters:     append([]Interceptor{}, ghq.inters...),
		predicates: append([]predicate.GameHistory{}, ghq.predicates...),
		withUser:   ghq.withUser.Clone(),
		withGame:   ghq.withGame.Clone(),
		// clone intermediate query.
		sql:  ghq.sql.Clone(),
		path: ghq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ghq *GameHistoryQuery) WithUser(opts ...func(*UserQuery)) *GameHistoryQuery {
	query := (&UserClient{config: ghq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ghq.withUser = query
	return ghq
}

// WithGame tells the query-builder to eager-load the nodes that are connected to
// the "game" edge. The optional arguments are used to configure the query builder of the edge.
func (ghq *GameHistoryQuery) WithGame(opts ...func(*ChessQuery)) *GameHistoryQuery {
	query := (&ChessClient{config: ghq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ghq.withGame = query
	return ghq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GameHistory.Query().
//		GroupBy(gamehistory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ghq *GameHistoryQuery) GroupBy(field string, fields ...string) *GameHistoryGroupBy {
	ghq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GameHistoryGroupBy{build: ghq}
	grbuild.flds = &ghq.ctx.Fields
	grbuild.label = gamehistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.GameHistory.Query().
//		Select(gamehistory.FieldCreatedAt).
//		Scan(ctx, &v)
func (ghq *GameHistoryQuery) Select(fields ...string) *GameHistorySelect {
	ghq.ctx.Fields = append(ghq.ctx.Fields, fields...)
	sbuild := &GameHistorySelect{GameHistoryQuery: ghq}
	sbuild.label = gamehistory.Label
	sbuild.flds, sbuild.scan = &ghq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GameHistorySelect configured with the given aggregations.
func (ghq *GameHistoryQuery) Aggregate(fns ...AggregateFunc) *GameHistorySelect {
	return ghq.Select().Aggregate(fns...)
}

func (ghq *GameHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ghq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ghq); err != nil {
				return err
			}
		}
	}
	for _, f := range ghq.ctx.Fields {
		if !gamehistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ghq.path != nil {
		prev, err := ghq.path(ctx)
		if err != nil {
			return err
		}
		ghq.sql = prev
	}
	return nil
}

func (ghq *GameHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GameHistory, error) {
	var (
		nodes       = []*GameHistory{}
		_spec       = ghq.querySpec()
		loadedTypes = [2]bool{
			ghq.withUser != nil,
			ghq.withGame != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GameHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GameHistory{config: ghq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ghq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ghq.withUser; query != nil {
		if err := ghq.loadUser(ctx, query, nodes, nil,
			func(n *GameHistory, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ghq.withGame; query != nil {
		if err := ghq.loadGame(ctx, query, nodes, nil,
			func(n *GameHistory, e *Chess) { n.Edges.Game = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ghq *GameHistoryQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*GameHistory, init func(*GameHistory), assign func(*GameHistory, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GameHistory)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ghq *GameHistoryQuery) loadGame(ctx context.Context, query *ChessQuery, nodes []*GameHistory, init func(*GameHistory), assign func(*GameHistory, *Chess)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*GameHistory)
	for i := range nodes {
		fk := nodes[i].GameID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chess.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ghq *GameHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ghq.querySpec()
	_spec.Node.Columns = ghq.ctx.Fields
	if len(ghq.ctx.Fields) > 0 {
		_spec.Unique = ghq.ctx.Unique != nil && *ghq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ghq.driver, _spec)
}

func (ghq *GameHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(gamehistory.Table, gamehistory.Columns, sqlgraph.NewFieldSpec(gamehistory.FieldID, field.TypeUUID))
	_spec.From = ghq.sql
	if unique := ghq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ghq.path != nil {
		_spec.Unique = true
	}
	if fields := ghq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamehistory.FieldID)
		for i := range fields {
			if fields[i] != gamehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ghq.withUser != nil {
			_spec.Node.AddColumnOnce(gamehistory.FieldUserID)
		}
		if ghq.withGame != nil {
			_spec.Node.AddColumnOnce(gamehistory.FieldGameID)
		}
	}
	if ps := ghq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ghq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ghq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ghq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ghq *GameHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ghq.driver.Dialect())
	t1 := builder.Table(gamehistory.Table)
	columns := ghq.ctx.Fields
	if len(columns) == 0 {
		columns = gamehistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ghq.sql != nil {
		selector = ghq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ghq.ctx.Unique != nil && *ghq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ghq.predicates {
		p(selector)
	}
	for _, p := range ghq.order {
		p(selector)
	}
	if offset := ghq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ghq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GameHistoryGroupBy is the group-by builder for GameHistory entities.
type GameHistoryGroupBy struct {
	selector
	build *GameHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ghgb *GameHistoryGroupBy) Aggregate(fns ...AggregateFunc) *GameHistoryGroupBy {
	ghgb.fns = append(ghgb.fns, fns...)
	return ghgb
}

// Scan applies the selector query and scans the result into the given value.
func (ghgb *GameHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ghgb.build.ctx, ent.OpQueryGroupBy)
	if err := ghgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GameHistoryQuery, *GameHistoryGroupBy](ctx, ghgb.build, ghgb, ghgb.build.inters, v)
}

func (ghgb *GameHistoryGroupBy) sqlScan(ctx context.Context, root *GameHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ghgb.fns))
	for _, fn := range ghgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ghgb.flds)+len(ghgb.fns))
		for _, f := range *ghgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ghgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ghgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GameHistorySelect is the builder for selecting fields of GameHistory entities.
type GameHistorySelect struct {
	*GameHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ghs *GameHistorySelect) Aggregate(fns ...AggregateFunc) *GameHistorySelect {
	ghs.fns = append(ghs.fns, fns...)
	return ghs
}

// Scan applies the selector query and scans the result into the given value.
func (ghs *GameHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ghs.ctx, ent.OpQuerySelect)
	if err := ghs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GameHistoryQuery, *GameHistorySelect](ctx, ghs.GameHistoryQuery, ghs, ghs.inters, v)
}

func (ghs *GameHistorySelect) sqlScan(ctx context.Context, root *GameHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ghs.fns))
	for _, fn := range ghs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ghs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ghs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
