name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          ENV: ${{ secrets.ENV }}

          DBHOST: ${{ secrets.DB_HOST }}
          DBPORT: ${{ secrets.DB_PORT }}
          DBUSER: ${{ secrets.DB_USER }}
          DBPASSWORD: ${{ secrets.DB_PASSWORD }}
          DBDATABASE: ${{ secrets.DB_DATABASE }}
          DBSSLMODE: ${{ secrets.DB_SSLMODE }}

          JWTSECRET: ${{ secrets.JWT_SECRET }}
          EXPTIME: ${{ secrets.EXP_TIME }}

          API_URL: ${{ secrets.API_URL }}
          WS_URL: ${{ secrets.WS_URL }}
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd GopherChessParty
            git pull origin main
            docker compose up -d --build