name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        env:
          REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}
          REACT_APP_WS_URL: ${{secrets.REACT_APP_API_URL}}
          ENV: ${{ secrets.ENV }}

          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          EXP_TIME: ${{ secrets.EXP_TIME }}

          API_URL: ${{ secrets.API_URL }}
          WS_URL: ${{ secrets.WS_URL }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd GopherChessParty
            git pull origin main
            docker compose up -d --build